#!/bin/sh
set -eu
PATH=`dirname "$0"`/../devutils:$PATH

# max distinguishable length of macro name in C89 is 31
macro=`random_identifier G_ 31`

cat <<EOF
#ifndef $macro
#define $macro
/*#include <_.h>*/
#ifdef __cplusplus
extern "C" {
#endif

/* code */

#ifdef __cplusplus
}
#endif
#endif
EOF
