#!/usr/bin/env python
import argparse, random, string

argparser = argparse.ArgumentParser()
argparser.add_argument(
    "prefix",
    nargs="?",
    default="",
)
argparser.add_argument(
    "length",
    type=int,
)

args = argparser.parse_args()
prefix = args.prefix
length = args.length

if not prefix:
    prefix = rng.choice(string.ascii_uppercase)
rng = random.SystemRandom()
print(prefix +
      "".join(rng.choice(string.ascii_uppercase + string.digits)
              for _ in range(length - len(prefix))))
